services:
  db:
    image: postgres:18.4-alpine3.24
    container_name: document-analyzer-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: document_analyzer
    ports:
      - "5433:5432"
    volumes:
      - document-analyzer-db-data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  document-analyzer-db-data:
