export const ANALYSIS_JSON_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    documentType: {
      type: 'string',
      enum: ['invoice', 'resume', 'contract', 'generic'],
    },
    confidence: { type: 'number', minimum: 0, maximum: 100 },
    summary: { type: 'string' },
    keyInfo: {
      type: 'object',
      additionalProperties: false,
      properties: {
        supplier: { type: ['string', 'null'] },
        customer: { type: ['string', 'null'] },
        invoiceNumber: { type: ['string', 'null'] },
        issueDate: { type: ['string', 'null'] },
        dueDate: { type: ['string', 'null'] },
        total: { type: ['number', 'null'] },
        currency: { type: ['string', 'null'] },
        fullName: { type: ['string', 'null'] },
        headline: { type: ['string', 'null'] },
        skills: { type: ['array', 'null'], items: { type: 'string' } },
        totalYearsExperience: { type: ['number', 'null'] },
        email: { type: ['string', 'null'] },
        phone: { type: ['string', 'null'] },
        parties: { type: ['array', 'null'], items: { type: 'string' } },
        startDate: { type: ['string', 'null'] },
        endDate: { type: ['string', 'null'] },
        value: { type: ['number', 'null'] },
      },
      required: [
        'supplier',
        'customer',
        'invoiceNumber',
        'issueDate',
        'dueDate',
        'total',
        'currency',
        'fullName',
        'headline',
        'skills',
        'totalYearsExperience',
        'email',
        'phone',
        'parties',
        'startDate',
        'endDate',
        'value',
      ],
    },
  },
  required: ['documentType', 'confidence', 'summary', 'keyInfo'],
};
