export const ANALYSIS_JSON_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    documentType: {
      type: 'string',
      enum: ['invoice', 'resume', 'contract', 'generic'],
    },
    confidence: { type: 'number', minimum: 0, maximum: 100 },
    summary: { type: 'string' },
    keyInfo: {
      type: 'object',
      additionalProperties: false,
      properties: {
        invoiceNumber: { type: ['string', 'null'] },
        date: { type: ['string', 'null'] },
        supplier: { type: ['string', 'null'] },
        customer: { type: ['string', 'null'] },
        subtotal: { type: ['number', 'null'] },
        tax: { type: ['number', 'null'] },
        total: { type: ['number', 'null'] },
        currency: { type: ['string', 'null'] },
        fullName: { type: ['string', 'null'] },
        email: { type: ['string', 'null'] },
        skills: { type: 'array', items: { type: 'string' } },
        experience: {
          type: 'array',
          items: {
            type: 'object',
            additionalProperties: false,
            properties: {
              company: { type: ['string', 'null'] },
              role: { type: ['string', 'null'] },
              startDate: { type: ['string', 'null'] },
              endDate: { type: ['string', 'null'] },
            },
            required: ['company', 'role', 'startDate', 'endDate'],
          },
        },
        education: {
          type: 'array',
          items: {
            type: 'object',
            additionalProperties: false,
            properties: {
              institution: { type: ['string', 'null'] },
              degree: { type: ['string', 'null'] },
              year: { type: ['string', 'null'] },
            },
            required: ['institution', 'degree', 'year'],
          },
        },
        parties: { type: 'array', items: { type: 'string' } },
        startDate: { type: ['string', 'null'] },
        endDate: { type: ['string', 'null'] },
        paymentTerms: { type: ['string', 'null'] },
        terminationConditions: { type: ['string', 'null'] },
      },
      required: [
        'invoiceNumber',
        'date',
        'supplier',
        'customer',
        'subtotal',
        'tax',
        'total',
        'currency',
        'fullName',
        'email',
        'skills',
        'experience',
        'education',
        'parties',
        'startDate',
        'endDate',
        'paymentTerms',
        'terminationConditions',
      ],
    },
  },
  required: ['documentType', 'confidence', 'summary', 'keyInfo'],
};
